#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# The one-time production setup from docs/deploy.md. Every stage checks what already exists,
# so re-run it after merging to main to finish the deploy, Scheduler and sign-in stages.

TOTAL_STAGES=13

cd "$(dirname "$0")/.."

# Values captured along the way live here (gitignored by `.env.*`), not in the dev .env.
ENV_FILE=.env.deploy
DEV_ENV=.env
REGION=northamerica-northeast1
REPO=aaronmanning613/myKOM

# Every gcloud call in this script uses its own configuration, so the active one is untouched.
export CLOUDSDK_ACTIVE_CONFIG_NAME=mykom

# ask_required KEY "Prompt": ask until the answer isn't empty.
ask_required() {
  while :; do
    ask "$1" "$2"
    [[ -n "${!1}" ]] && return
    warn "this one is required"
  done
}

# seed_from_dev KEY: copy KEY from the dev .env into ENV_FILE as the default, if missing there.
seed_from_dev() {
  local value
  _existing "$1" >/dev/null && return 0
  [[ -f "$DEV_ENV" ]] || return 0
  value=$(grep -E "^${1}=" "$DEV_ENV" | tail -n1 | cut -d= -f2-) || return 0
  [[ -n "$value" ]] || return 0
  write_env "$1" "$value"
  note "(taken from $DEV_ENV; Enter keeps it)"
}

# retry CMD...: new service accounts take a few seconds to be visible to IAM.
retry() {
  local i
  for i in 1 2 3 4 5 6; do
    "$@" >/dev/null 2>&1 && return 0
    sleep 5
  done
  "$@" >/dev/null
}

exists() { "$@" >/dev/null 2>&1; }

banner "myKOM production setup (docs/deploy.md)"

# ── 0 ─────────────────────────────────────────────────────────────────────
stage "gcloud: a personal 'mykom' configuration"
say "Your active gcloud configuration stays as it is. This script uses its own one, 'mykom'."
if ! exists gcloud config configurations describe mykom; then
  gcloud config configurations create mykom --no-activate >/dev/null 2>&1
  printf '  %s✓ created%s gcloud configuration mykom\n' "$GREEN" "$RESET"
fi
ask_required GCLOUD_ACCOUNT "Google account for myKOM's GCP project (your personal one):"
write_env GCLOUD_ACCOUNT "$GCLOUD_ACCOUNT"
gcloud config set account "$GCLOUD_ACCOUNT" >/dev/null 2>&1
if [[ -z "$(gcloud auth list --filter="account:$GCLOUD_ACCOUNT" --format='value(account)' 2>/dev/null)" ]]; then
  step "A browser will open. Sign in as $GCLOUD_ACCOUNT."
  gcloud auth login "$GCLOUD_ACCOUNT"
fi
printf '  %s✓%s gcloud in this script runs as %s\n' "$GREEN" "$RESET" "$GCLOUD_ACCOUNT"
if ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't signed in. Run 'gh auth login' in another terminal before stage 8."
fi
pause

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase: database and its session-pooler URL"
open_url "https://supabase.com/dashboard/new"
step "Create a new project on the Free plan, with region Canada (Central) (ca-central-1)."
step "Generate the database password and save it in your password manager."
step "When the project is ready, click Connect at the top of its dashboard."
step "Under Session pooler (not Direct connection: that's IPv6-only), copy the URI."
step "Replace [YOUR-PASSWORD] with the password, and add ?sslmode=require at the end."
note "postgres://postgres.<ref>:<password>@aws-0-ca-central-1.pooler.supabase.com:5432/postgres?sslmode=require"
while :; do
  ask_secret PROD_DATABASE_URL "Paste the full session-pooler URL:"
  [[ "$PROD_DATABASE_URL" == postgres*://*pooler.supabase.com:5432/* ]] && break
  warn "that doesn't look like a session-pooler URL (…pooler.supabase.com:5432/…)"
done
if command -v psql >/dev/null 2>&1; then
  if psql "$PROD_DATABASE_URL" -tAc 'select 1' >/dev/null 2>&1; then
    printf '  %s✓%s connected to the database\n' "$GREEN" "$RESET"
  else
    warn "psql couldn't connect. Check the password and try again before going on."
    exit 1
  fi
fi
write_env PROD_DATABASE_URL "$PROD_DATABASE_URL"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GCP: the project and its billing account"
note "A project id is 6–30 lowercase letters, digits and hyphens, unique across all of GCP."
ask_required GCP_PROJECT_ID "Project id (e.g. mykom-$(date +%y%m)):"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
if exists gcloud projects describe "$GCP_PROJECT_ID"; then
  printf '  %s✓%s project %s exists\n' "$GREEN" "$RESET" "$GCP_PROJECT_ID"
elif confirm "Create project $GCP_PROJECT_ID?"; then
  gcloud projects create "$GCP_PROJECT_ID"
else
  warn "stopping: the rest needs the project"; exit 1
fi
gcloud config set project "$GCP_PROJECT_ID" >/dev/null 2>&1
gcloud config set billing/quota_project "$GCP_PROJECT_ID" >/dev/null 2>&1
PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')

if [[ "$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingEnabled)')" == "True" ]]; then
  printf '  %s✓%s billing is linked\n' "$GREEN" "$RESET"
fi
say "Your open billing accounts:"
gcloud billing accounts list --filter=open=true --format='table(name.basename():label=ACCOUNT_ID,displayName)' | sed 's/^/    /'
note "None listed? Create one at https://console.cloud.google.com/billing, then re-run."
ask_required GCP_BILLING_ACCOUNT_ID "Billing ACCOUNT_ID to use:"
write_env GCP_BILLING_ACCOUNT_ID "$GCP_BILLING_ACCOUNT_ID"
if [[ "$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingEnabled)')" != "True" ]]; then
  gcloud billing projects link "$GCP_PROJECT_ID" --billing-account="$GCP_BILLING_ACCOUNT_ID" >/dev/null
  printf '  %s✓ linked%s billing account %s\n' "$GREEN" "$RESET" "$GCP_BILLING_ACCOUNT_ID"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "GCP: APIs and the \$1 budget alert"
say "Turning on the APIs (this can take a minute)…"
gcloud services enable run.googleapis.com artifactregistry.googleapis.com \
  secretmanager.googleapis.com cloudscheduler.googleapis.com iamcredentials.googleapis.com \
  sts.googleapis.com billingbudgets.googleapis.com logging.googleapis.com
printf '  %s✓%s APIs enabled\n' "$GREEN" "$RESET"
BUDGET_NAME='myKOM $1'
if [[ -n "$(gcloud billing budgets list --billing-account="$GCP_BILLING_ACCOUNT_ID" \
      --filter="displayName=\"$BUDGET_NAME\"" --format='value(name)' 2>/dev/null)" ]]; then
  printf '  %s✓%s the budget alert already exists\n' "$GREEN" "$RESET"
else
  gcloud billing budgets create --billing-account="$GCP_BILLING_ACCOUNT_ID" \
    --display-name="$BUDGET_NAME" --budget-amount=1USD \
    --filter-projects="projects/$GCP_PROJECT_ID" --threshold-rule=percent=1.0 >/dev/null
  printf '  %s✓ created%s a budget that emails billing admins at \$1 of actual spend\n' "$GREEN" "$RESET"
fi
note "It only alerts. Nothing gets shut down."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Artifact Registry: the image repository"
if exists gcloud artifacts repositories describe mykom --location="$REGION"; then
  printf '  %s✓%s repository mykom exists\n' "$GREEN" "$RESET"
else
  gcloud artifacts repositories create mykom --repository-format=docker --location="$REGION"
fi
CLEANUP=$(mktemp)
cat > "$CLEANUP" <<'EOF'
[
  { "name": "keep-last-3", "action": { "type": "Keep" }, "mostRecentVersions": { "keepCount": 3 } },
  { "name": "delete-older", "action": { "type": "Delete" }, "condition": { "tagState": "any" } }
]
EOF
gcloud artifacts repositories set-cleanup-policies mykom --location="$REGION" \
  --policy="$CLEANUP" --no-dry-run >/dev/null
rm -f "$CLEANUP"
printf '  %s✓%s cleanup policy: keep the last 3 images\n' "$GREEN" "$RESET"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Service accounts: deploy, runtime and scheduler"
for name in mykom-deploy mykom-runtime mykom-scheduler; do
  if exists gcloud iam service-accounts describe "$name@$GCP_PROJECT_ID.iam.gserviceaccount.com"; then
    printf '  %s✓%s %s exists\n' "$GREEN" "$RESET" "$name"
  else
    gcloud iam service-accounts create "$name" >/dev/null
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$name"
  fi
done
DEPLOY_SA=mykom-deploy@$GCP_PROJECT_ID.iam.gserviceaccount.com
RUNTIME_SA=mykom-runtime@$GCP_PROJECT_ID.iam.gserviceaccount.com
SCHEDULER_SA=mykom-scheduler@$GCP_PROJECT_ID.iam.gserviceaccount.com
say "Granting roles…"
retry gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
  --member="serviceAccount:$DEPLOY_SA" --role=roles/run.admin --condition=None --quiet
retry gcloud artifacts repositories add-iam-policy-binding mykom --location="$REGION" \
  --member="serviceAccount:$DEPLOY_SA" --role=roles/artifactregistry.writer
retry gcloud iam service-accounts add-iam-policy-binding "$RUNTIME_SA" \
  --member="serviceAccount:$DEPLOY_SA" --role=roles/iam.serviceAccountUser
printf '  %s✓%s deploy can deploy Cloud Run, push images, and run the service as runtime\n' "$GREEN" "$RESET"
note "scheduler needs no roles: the app checks its token itself."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Secret Manager: the four secrets"
# create_secret NAME: reads the value from stdin; never overwrites an existing secret.
create_secret() {
  if exists gcloud secrets describe "$1"; then
    cat >/dev/null
    printf '  %s✓%s %s exists (kept)\n' "$GREEN" "$RESET" "$1"
  else
    gcloud secrets create "$1" --data-file=- >/dev/null
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$1"
  fi
}
seed_from_dev STRAVA_CLIENT_SECRET
if ! _existing STRAVA_CLIENT_SECRET >/dev/null; then
  open_url "https://www.strava.com/settings/api"
  step "Under My API Application, show the Client Secret and copy it."
fi
while :; do
  ask_secret STRAVA_CLIENT_SECRET "Strava client secret:"
  [[ -n "$STRAVA_CLIENT_SECRET" ]] && break
  warn "this one is required"
done
write_env STRAVA_CLIENT_SECRET "$STRAVA_CLIENT_SECRET"

printf '%s' "$PROD_DATABASE_URL" | create_secret DATABASE_URL
openssl rand -base64 32 | tr -d '\n' | create_secret SESSION_SECRET
printf '%s' "$STRAVA_CLIENT_SECRET" | create_secret STRAVA_CLIENT_SECRET
openssl rand -base64 32 | tr -d '\n' | create_secret TOKEN_ENCRYPTION_KEY
note "To change DATABASE_URL or the Strava secret later: gcloud secrets versions add NAME --data-file=-"
warn "Never change TOKEN_ENCRYPTION_KEY: stored Strava tokens couldn't be read."

for secret in DATABASE_URL SESSION_SECRET STRAVA_CLIENT_SECRET TOKEN_ENCRYPTION_KEY; do
  retry gcloud secrets add-iam-policy-binding "$secret" \
    --member="serviceAccount:$RUNTIME_SA" --role=roles/secretmanager.secretAccessor
done
retry gcloud secrets add-iam-policy-binding TOKEN_ENCRYPTION_KEY \
  --member="serviceAccount:$DEPLOY_SA" --role=roles/secretmanager.secretAccessor
printf '  %s✓%s runtime reads all four; deploy reads TOKEN_ENCRYPTION_KEY (for migrations)\n' "$GREEN" "$RESET"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Workload Identity Federation: GitHub main → the deploy account"
if exists gcloud iam workload-identity-pools describe github --location=global; then
  printf '  %s✓%s pool github exists\n' "$GREEN" "$RESET"
else
  gcloud iam workload-identity-pools create github --location=global --display-name=GitHub >/dev/null
  printf '  %s✓ created%s pool github\n' "$GREEN" "$RESET"
fi
if exists gcloud iam workload-identity-pools providers describe github --location=global --workload-identity-pool=github; then
  printf '  %s✓%s provider github exists\n' "$GREEN" "$RESET"
else
  gcloud iam workload-identity-pools providers create-oidc github --location=global \
    --workload-identity-pool=github --issuer-uri=https://token.actions.githubusercontent.com \
    --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository,attribute.ref=assertion.ref" \
    --attribute-condition="assertion.repository=='$REPO' && assertion.ref=='refs/heads/main'" >/dev/null
  printf '  %s✓ created%s provider github (only %s on main)\n' "$GREEN" "$RESET" "$REPO"
fi
retry gcloud iam service-accounts add-iam-policy-binding "$DEPLOY_SA" --role=roles/iam.workloadIdentityUser \
  --member="principalSet://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/github/attribute.repository/$REPO"
WIF_PROVIDER="projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/github/providers/github"
printf '  %s✓%s GitHub Actions may act as %s\n' "$GREEN" "$RESET" "$DEPLOY_SA"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the Actions secret and variables"
SERVICE_URL="https://mykom-$PROJECT_NUMBER.$REGION.run.app"
write_env SERVICE_URL "$SERVICE_URL"
seed_from_dev STRAVA_CLIENT_ID
ask_required STRAVA_CLIENT_ID "Strava client ID (the number on strava.com/settings/api):"
write_env STRAVA_CLIENT_ID "$STRAVA_CLIENT_ID"
seed_from_dev NOMINATIM_USER_AGENT
note "Nominatim wants the app name and a contact, e.g. myKOM/1.0 (you@example.com)."
ask_required NOMINATIM_USER_AGENT "Nominatim user agent:"
write_env NOMINATIM_USER_AGENT "$NOMINATIM_USER_AGENT"
say "Writing to $REPO…"
set_secret DATABASE_URL "$PROD_DATABASE_URL"
set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$WIF_PROVIDER"
set_var GCP_DEPLOY_SERVICE_ACCOUNT "$DEPLOY_SA"
set_var GCP_RUNTIME_SERVICE_ACCOUNT "$RUNTIME_SA"
set_var GCP_SCHEDULER_SERVICE_ACCOUNT "$SCHEDULER_SA"
set_var SERVICE_URL "$SERVICE_URL"
set_var STRAVA_CLIENT_ID "$STRAVA_CLIENT_ID"
set_var NOMINATIM_USER_AGENT "$NOMINATIM_USER_AGENT"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Strava: the callback domain and athlete limit"
SERVICE_HOST=${SERVICE_URL#https://}
open_url "https://www.strava.com/settings/api"
step "Click Edit and set Authorization Callback Domain to exactly:"
printf '\n      %s%s%s\n\n' "$BOLD" "$SERVICE_HOST" "$RESET"
note "No https://. localhost is always allowed, so local dev keeps working."
step "Save."
step "If the page offers raising the athlete limit, request 10 athletes."
note "Until then the app works for you (the app owner) only."
pause "Done with Strava? Press Enter"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "The first deploy"
DEPLOYED=false
if exists gcloud run services describe mykom --region="$REGION"; then
  DEPLOYED=true
else
  say "Cloud Run has no mykom service yet. Every push to main deploys, so:"
  step "Merge ralph/core into main (open a PR, review it, merge)."
  step "Watch the Deploy workflow: gh run watch (or the Actions tab)."
  open_url "https://github.com/$REPO/actions/workflows/deploy.yml"
  if confirm "Has a Deploy run finished green just now?"; then
    exists gcloud run services describe mykom --region="$REGION" && DEPLOYED=true
  fi
fi
if $DEPLOYED; then
  HEALTH=$(curl -fsS "$SERVICE_URL/api/health" 2>/dev/null || true)
  if [[ "$HEALTH" == *'"ok":true'* ]]; then
    printf '  %s✓%s %s/api/health → %s\n' "$GREEN" "$RESET" "$SERVICE_URL" "$HEALTH"
  else
    warn "health check didn't say ok: '${HEALTH:-no response}'. See the Cloud Run logs."
  fi
else
  SKIPPED+=("first deploy: merge to main, wait for Deploy to go green, then re-run this script")
  warn "not deployed yet. Re-run this script afterwards; it'll skip what's done."
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Cloud Scheduler: the 5-minute tick"
if ! $DEPLOYED; then
  SKIPPED+=("the Scheduler tick (after the first deploy)")
  note "Skipped until the service is deployed."
else
  if exists gcloud scheduler jobs describe mykom-tick --location="$REGION"; then
    printf '  %s✓%s job mykom-tick exists\n' "$GREEN" "$RESET"
  else
    gcloud scheduler jobs create http mykom-tick --location="$REGION" \
      --schedule="*/5 * * * *" --http-method=POST --uri="$SERVICE_URL/internal/tick" \
      --oidc-service-account-email="$SCHEDULER_SA" --oidc-token-audience="$SERVICE_URL" >/dev/null
    printf '  %s✓ created%s job mykom-tick (POST /internal/tick every 5 minutes)\n' "$GREEN" "$RESET"
  fi
  gcloud scheduler jobs run mykom-tick --location="$REGION"
  say "Ran it once; waiting 30 s for the request to show in the logs…"
  sleep 30
  TICK_STATUS=$(gcloud logging read \
    'resource.type="cloud_run_revision" AND httpRequest.requestUrl:"/internal/tick"' \
    --freshness=5m --limit=1 --format='value(httpRequest.status)' 2>/dev/null || true)
  case "$TICK_STATUS" in
    200) printf '  %s✓%s the tick answered 200\n' "$GREEN" "$RESET" ;;
    401) warn "401: the token's audience or account doesn't match SERVICE_URL / GCP_SCHEDULER_SERVICE_ACCOUNT" ;;
    "")  warn "no tick in the logs yet. Check Cloud Run → mykom → Logs in a minute." ;;
    *)   warn "the tick answered $TICK_STATUS. Check Cloud Run → mykom → Logs." ;;
  esac
fi
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Sign in and search"
if ! $DEPLOYED; then
  SKIPPED+=("sign in at $SERVICE_URL and run a search (after the first deploy)")
  note "Skipped until the service is deployed."
else
  open_url "$SERVICE_URL"
  step "Sign in with Strava. The first sync of all your runs can take about a minute."
  step "Walk the wizard, run a search, and check that Results fill in."
  note "Use exactly this URL (not Cloud Run's older hashed one): the tick and Strava callback rely on it."
  pause "Signed in and searched? Press Enter"
fi

finish
say "Service URL: $SERVICE_URL"
say "Captured values are in $ENV_FILE (gitignored). Delete it once you're done if you like."
printf '\n'
